const ON_PAGE_SIZE_CHANGE = "ON_PAGE_SIZE_CHANGE";
const ON_PAGE_CHANGE = "ON_PAGE_CHANGE";
const DO_SEARCH = "HAS_ERROR";

module.exports = {
    ON_PAGE_SIZE_CHANGE,
    ON_PAGE_CHANGE,
    DO_SEARCH,
}
