const ON_PAGE_SIZE_CHANGE = "ON_PAGE_SIZE_CHANGE";
const ON_PAGE_CHANGE = "ON_PAGE_CHANGE";
const ON_NATION_CHANGE = 'ON_NATION_CHANGE';
const DO_SEARCH = "HAS_ERROR";

export {
    ON_PAGE_SIZE_CHANGE,
    ON_PAGE_CHANGE,
    ON_NATION_CHANGE,
    DO_SEARCH,
}
